# Generate the real k8s\secret.yaml from the git-ignored .\.env
# (PowerShell 5.1-compatible twin of gen-secret.sh).
#
#   powershell -File k8s\scripts\gen-secret.ps1
#   kubectl apply -f k8s\secret.yaml
#
# Never prints a value. The output file is git-ignored.
$ErrorActionPreference = 'Stop'

$root    = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$envFile = Join-Path $root '.env'
$out     = Join-Path $root 'k8s\secret.yaml'

if (-not (Test-Path $envFile)) {
    throw "$envFile not found. Copy .env.example to .env and fill it in."
}

# Parse KEY=value without executing the file - a stray character in a password
# must never be run as code.
$envMap = @{}
foreach ($line in Get-Content $envFile) {
    if ($line -match '^\s*#') { continue }
    if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
        $envMap[$Matches[1]] = $Matches[2].Trim().Trim('"').Trim("'")
    }
}

$pgUser = $envMap['POSTGRES_USER']
$pgPass = $envMap['POSTGRES_PASSWORD']
$jwt    = $envMap['JWT_SECRET']
$aiKey  = $envMap['OPENAI_API_KEY']
if ($null -eq $aiKey) { $aiKey = '' }

foreach ($pair in @(@('POSTGRES_USER', $pgUser), @('POSTGRES_PASSWORD', $pgPass), @('JWT_SECRET', $jwt))) {
    if ([string]::IsNullOrWhiteSpace($pair[1])) { throw "$($pair[0]) is empty in $envFile" }
}

# Single-quoted YAML scalar: doubling an embedded quote is the only escape YAML
# needs, so passwords containing $ \ : # survive verbatim.
function Quote-Yaml([string]$v) { "'" + $v.Replace("'", "''") + "'" }

$content = @"
# GENERATED by k8s/scripts/gen-secret.ps1 from ./.env - DO NOT COMMIT.
# git-ignored via k8s/**/*secret*.yaml (only secret.example.yaml is committed).
#
# A Kubernetes Secret is base64-ENCODED, not encrypted: anyone who can read
# this file, or run ``kubectl get secret finquest-secrets -o yaml``, has the
# credentials. Regenerate it instead of editing it by hand.
apiVersion: v1
kind: Secret
metadata:
  name: finquest-secrets
  labels:
    app.kubernetes.io/part-of: finquest
type: Opaque
stringData:
  POSTGRES_USER: $(Quote-Yaml $pgUser)
  POSTGRES_PASSWORD: $(Quote-Yaml $pgPass)
  JWT_SECRET: $(Quote-Yaml $jwt)
  OPENAI_API_KEY: $(Quote-Yaml $aiKey)
"@

# utf8 without BOM would be ideal; kubectl tolerates the BOM, but strip it anyway.
[System.IO.File]::WriteAllText($out, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Wrote $out (values not printed)."
if ([string]::IsNullOrWhiteSpace($aiKey)) {
    Write-Host "Note: OPENAI_API_KEY is empty - the mentor will serve its static messages."
}
Write-Host "Next: kubectl apply -f k8s\secret.yaml"
