#!/bin/sh
# Generate the real k8s/secret.yaml from the git-ignored ./.env.
#
# Why a generator instead of hand-editing: the credentials already live in one
# place (./.env, used by docker-compose). Copying them into a second file by
# hand is how a secret ends up committed. This writes the git-ignored twin of
# secret.example.yaml and never prints a value.
#
#   sh k8s/scripts/gen-secret.sh
#   kubectl apply -f k8s/secret.yaml
set -e

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/k8s/secret.yaml"

[ -f "$ENV_FILE" ] || { echo "ERROR: $ENV_FILE not found. Copy .env.example to .env and fill it in." >&2; exit 1; }

# Read KEY=value without sourcing the file — a stray shell character in a
# password must not be executed.
read_env() {
  sed -n "s/^[[:space:]]*$1=//p" "$ENV_FILE" | tail -n 1 \
    | sed 's/[[:space:]]*$//; s/^"\(.*\)"$/\1/; s/^'"'"'\(.*\)'"'"'$/\1/'
}

POSTGRES_USER="$(read_env POSTGRES_USER)"
POSTGRES_PASSWORD="$(read_env POSTGRES_PASSWORD)"
JWT_SECRET="$(read_env JWT_SECRET)"
OPENAI_API_KEY="$(read_env OPENAI_API_KEY)"

for v in POSTGRES_USER POSTGRES_PASSWORD JWT_SECRET; do
  eval "val=\$$v"
  [ -n "$val" ] || { echo "ERROR: $v is empty in $ENV_FILE" >&2; exit 1; }
done

# Single-quoted YAML scalars: doubling any embedded quote is the only escape
# YAML needs, so passwords with $ \ : # survive verbatim.
yq_quote() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/''/g")"; }

cat > "$OUT" <<EOF
# GENERATED by k8s/scripts/gen-secret.sh from ./.env — DO NOT COMMIT.
# git-ignored via k8s/**/*secret*.yaml (only secret.example.yaml is committed).
#
# A Kubernetes Secret is base64-ENCODED, not encrypted: anyone who can read
# this file, or run \`kubectl get secret finquest-secrets -o yaml\`, has the
# credentials. Regenerate it instead of editing it by hand.
apiVersion: v1
kind: Secret
metadata:
  name: finquest-secrets
  labels:
    app.kubernetes.io/part-of: finquest
type: Opaque
stringData:
  POSTGRES_USER: $(yq_quote "$POSTGRES_USER")
  POSTGRES_PASSWORD: $(yq_quote "$POSTGRES_PASSWORD")
  JWT_SECRET: $(yq_quote "$JWT_SECRET")
  OPENAI_API_KEY: $(yq_quote "$OPENAI_API_KEY")
EOF

echo "Wrote $OUT (values not printed)."
[ -n "$OPENAI_API_KEY" ] || echo "Note: OPENAI_API_KEY is empty — the mentor will serve its static messages."
echo "Next: kubectl apply -f k8s/secret.yaml"
